language: php

php:
    - 5.6
    - 7.0

addons:
  firefox: 43.0

sudo: false
cache:
  directories:
    - node_modules
    - vendor

before_script:
    - curl -L git.io/nodebrew | perl - setup
    - export PATH=$HOME/.nodebrew/current/bin:$PATH
    - nodebrew install-binary 5.2.0
    - nodebrew use 5.2.0
    - cp -p .env.example .env
    - composer self-update
    - composer install
    - php artisan key:generate
    - php artisan serve
    - npm install
    - node_modules/.bin/gulp
    - node_modules/.bin/typings install
    - node_modules/.bin/gulp tsbuild
    - node_modules/.bin/webdriver-manager update

script:
    - mkdir -p build/logs
    - chmod -R 777 build/logs
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - node_modules/.bin/gulp tsbuild
    - sh -e /etc/init.d/xvfb start

after_success:
    - travis_retry php vendor/bin/coveralls -v
    - node_modules/.bin/protractor e2efirefox.js
    - node_modules/.bin/protractor e2ephantom.js