language: php

php:
    - 5.6
    - 7.0
    - hhvm
    - nightly

before_script:
    - cp -p .env.example .env
    - composer self-update
    - composer install
    - php artisan key:generate

script:
    - mkdir -p build/logs
    - chmod -R 777 build/logs
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls -v