language: php

before_script:
    - cp -p .env.example .env
    - composer self-update
    - composer install
    - php artisan key:generate

php:
    - 5.6
    - 7.0
    - hhvm
    - nightly

script:
  - vendor/bin/phpunit