language: php

php:
    - 5.6
    - 7.0
    - hhvm
    - nightly

before_script:
    - cp -p .env.example .env
    - composer self-update
    - composer install
    - php artisan key:generate
    - npm install
    - node_modules/.bin/gulp
    - node_modules/.bin/gulp tsbuild

script:
    - mkdir -p build/logs
    - chmod -R 777 build/logs
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - node_modules/.bin/gulp tsbuild

after_success:
    - travis_retry php vendor/bin/coveralls -v
    - node_modules/.bin/protractor e2ephantom.js