language: php

php:
    - 5.6
    - 7.0

addons:
  firefox: 43.0

sudo: false
cache:
  directories:
    - node_modules
    - vendor
    - typings

before_install:
    - curl -L git.io/nodebrew | perl - setup
    - export PATH=$HOME/.nodebrew/current/bin:$PATH
    - nodebrew install-binary 5.2.0
    - nodebrew use 5.2.0
    - cp -p .env.example .env
    - composer self-update
    - composer install
    - php artisan key:generate
    - npm install
    
install:
    - node_modules/.bin/typings install

before_script:
    # - "export DISPLAY=:99.0"
    # - "sh -e /etc/init.d/xvfb start"
    # - sleep 3
    - php artisan serve &
    - node_modules/.bin/gulp
    - node_modules/.bin/gulp tsbuild
    # - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
    # - node_modules/protractor/bin/webdriver-manager update
    # - node_modules/protractor/bin/webdriver-manager start &

script:
    - mkdir -p build/logs
    - chmod -R 777 build/logs
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - node_modules/.bin/gulp tsbuild

after_success:
    - travis_retry php vendor/bin/coveralls -v
    # - node_modules/.bin/protractor e2efirefox.js
    # - node_modules/.bin/protractor e2ephantom.js