version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "igara"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "igara"
    allowed_updates:
      - match:
          update_type: "security"
